apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: keyyds/docker-fastapi:274b05d703b685f49bfb57d77ffbee3b7d26798f
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
