apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: keyyds/docker-fastapi:dcff658e73f97b78ab8160f4953e0ebb61384624
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
