apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: keyyds/docker-fastapi:3ec4a0caa8cc8f396cb68b4ba9c753d0ce3f5e59
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
